package it.sogei.svildep.istanzaservice.service;

import it.sogei.svildep.istanzaservice.dto.istanza.depositoAmministrativo.IstanzaDepositoAmministrativoNoEsproprioDto;
import it.sogei.svildep.istanzaservice.mapper.istanza.depositoAmministrativo.IstanzaDepositoAmministrativoNoEsproprioMapper;
import it.sogei.svildep.istanzaservice.model.istanza.depositoAmministrativo.IstanzaDepositoAmministrativoNoEsproprio;
import it.sogei.svildep.istanzaservice.repository.IstanzaDepositoAmministrativoNoEsproprioRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class IstanzaDepositoAmministrativoNoEsproprioService extends IstanzaService<IstanzaDepositoAmministrativoNoEsproprio, IstanzaDepositoAmministrativoNoEsproprioDto> {

    private final IstanzaDepositoAmministrativoNoEsproprioRepository repository;
    private final IstanzaDepositoAmministrativoNoEsproprioMapper mapper;
}
