package it.sogei.svildep.utenteservice.util;

public interface LoremIpsum {

	public static final String[] NOMI = { "Abramo", "Acantha", "Ace", "Achille", "Ada", "Adamo",
			"Adelaide", "Adele", "Adimar", "Adina", "Adolfo", "Adorno", "Adriana", "Adriano",
			"Adriel", "Adriele", "Afra", "Agar", "Agata", "Agave", "Agnese", "Agostino", "Aimeu'",
			"Alan", "Alarico", "Alba", "Albano", "Alberta", "Alberto", "Albino", "Alcina", "Alda",
			"Aldo", "Aldobrando", "Aldwin", "Alea", "Aleramo", "Alessandra", "Alessandro",
			"Alessia", "Alessio", "Alfio", "Alfonsina", "Alfonso", "Alfredo", "Alhena", "Alia",
			"Alice", "Alida", "Alina", "Allegra", "Alma", "Altair", "Altea", "Alvaro", "Alvina",
			"Amalia", "Amanda", "Amaranta", "Amarilli", "Ambra", "Ambrogio", "Amedeo", "Amina",
			"Amos", "Anastasia", "Ancilla", "Andrea", "Andreina", "Andromeda", "Angela", "Angelica",
			"Angelo", "Annika", "Anna", "Annunziata", "Anselmo", "Antonia", "Antonio", "Aquilante",
			"Arabella", "Aramis", "Arduino", "Aretha", "Argelia", "Aria", "Arianna", "Ariele",
			"Ariella", "Aristide", "Arlena", "Armando", "Armida", "Arnaldo", "Aroldo", "Arturo",
			"Ashton", "Aspasia", "Assunta", "Asteria", "Athos", "Attilio", "Audrey", "Augusta",
			"Augusto", "Aura", "Aurea", "Aurelio", "Aurora", "Axel", "Azalea", "Azzurra", "Baldo",
			"Baldovino", "Balthazar", "Barbara", "Bardo", "Bartolomeo", "Battista", "Beatrice",
			"Belinda", "Bella", "Ben", "Benedetto", "Beniamino", "Benvenuto", "Bernardo", "Berta",
			"Bertrando", "Beryl", "Bianca", "Bibiana", "Bjorn", "Boris", "Brad", "Brent", "Brian",
			"Brigida", "Bruna", "Brunilde", "Bruno", "Bud", "Caio", "Calogero", "Calypso",
			"Camelia", "Cameron", "Camilla", "Camillo", "Candida", "Candido", "Carina", "Carla",
			"Carlo", "Carmela", "Carmelo", "Carolina", "Cassandra", "Caterina", "Cecilia", "Cedric",
			"Celesta", "Celeste", "Cesara", "Cesare", "Chandra", "Chantal", "Chiara", "Cino",
			"Cinzia", "Cirillo", "Ciro", "Claudia", "Claudio", "Clelia", "Clemente", "Clio",
			"Clizia", "Cloe", "Clorinda", "Clotilde", "Concetta", "Consolata", "Contessa", "Cora",
			"Cordelia", "Corinna", "Cornelia", "Corrado", "Cosetta", "Cosimo", "Costantino",
			"Costanza", "Costanzo", "Cristal", "Cristiana", "Cristiano", "Cristina", "Cristoforo",
			"Cruz", "Curzio", "Dafne", "Dagmar", "Dagon", "Daisy", "Dalia", "Dalila", "Damaris",
			"Damiano", "Danae", "Daniela", "Daniele", "Dante", "Daria", "Dario", "Davide", "Dean",
			"Debora", "Dela", "Delfino", "Delia", "Delizia", "Demetrio", "Demos", "Dermont",
			"Desdemona", "Deva", "Diamante", "Diana", "Diego", "Diletta", "Dina", "Dino", "Dionigi",
			"Diva", "Dolcina", "Dolores", "Domenica", "Domenico", "Domitilla", "Donald", "Donar",
			"Donata", "Donato", "Donna", "Dora", "Doriana", "Doriano", "Doris", "Dorotea",
			"Douglas", "Drago", "Drusiana", "Duccio", "Duilio", "Duncan", "Dylan", "Ebe", "Eco",
			"Edda", "Edelweiss", "Eden", "Edera", "Edgardo", "Edith", "Ediardo", "Edvige", "Edwin",
			"Efraim", "Egeria", "Egidio", "Eglantina", "Egle", "Einar", "Elda", "Eldora", "Elena",
			"Eleonora", "Eletta", "Elettra", "Elfo", "Elga", "Elia", "Eliana", "Eligio", "Elio",
			"Elisabetta", "Elissa", "Ella", "Elsa", "Elvino", "Elvio", "Elvira", "Elvis",
			"Emanuela", "Emanuele", "Emilia", "Emiliana", "Emiliano", "Emilio", "Emma", "Enea",
			"Enki", "Ennio", "Enrica", "Enrico", "Enza", "Enzo", "Eolo", "Era", "Erasmo", "Erica",
			"Eris", "Ermanno", "Ermes", "Erminio", "Ernesto", "Eros", "Esmeralda", "Ester", "Ethel",
			"Etilla", "Ettore", "Eudora", "Eugenia", "Eugenio", "Euridice", "Euro", "Eva", "Evania",
			"Evelina", "Ezio", "Fabiana", "Fabiano", "Fabio", "Fabrizia", "Fabrizio", "Faith",
			"Falco", "Fara", "Fatima", "Fausta", "Fausto", "Febo", "Fedele", "Federica", "Federico",
			"Fedra", "Felice", "Feliciano", "Felicita", "Fenella", "Ferdinando", "Fergal", "Fergus",
			"Fermo", "Fernanda", "Fernando", "Ferruccio", "Fiammetta", "Filiberto", "Filippo",
			"Fillide", "Filomena", "Fiona", "Fiore", "Fiorella", "Fiorenza", "Fiorenzo", "Flaminia",
			"Flaminio", "Flavia", "Flavio", "Flora", "Floriano", "Folco", "Ford", "Fortuna",
			"Fortunato", "Franca", "Francesca", "Francesco", "Franco", "Freya", "Frida", "Frine",
			"Fulvia", "Fulvio", "Furio", "Gabriele", "Gabriella", "Gaetano", "Gaia", "Gail",
			"Galtea", "Galeazzo", "Gardenia", "Gareth", "Gaspare", "Gastone", "Gavin", "Gaynor",
			"Gea", "Gelsomina", "Geltrude", "Gemma", "Gennaro", "Genoveffa", "Genziana", "Gerardo",
			"Gerda", "Germano", "Ghino", "Giacomo", "Giada", "Gigliola", "Gilberto", "Gilda",
			"Ginestra", "Ginevra", "Gioia", "Giole", "Giona", "Giordano", "Giorgio", "Giotto",
			"Giovanna", "Giovanni", "Gisella", "Giuditta", "Giulia", "Giuliana", "Giuliano",
			"Giulio", "Giunia", "Giuseppe", "Giuseppina", "Glauco", "Glen", "Glenda", "Glicera",
			"Gloria", "Godiva", "Goffredo", "Goliard", "Gordon", "Graham", "Grant", "Grazia",
			"Graziana", "Graziano", "Gregorio", "Griselda", "Gualtiero", "Guendalina", "Guerrino",
			"Guglielmo", "Guicciardo", "Guido", "Gunnar", "Gurthie", "Gustavo", "Haidar", "Haila",
			"Harrison", "Hassan", "Haydee", "Heather", "Hela", "Hidalgo", "Hiram", "Holger",
			"Hoshi", "Hasib", "Ida", "Idalia", "Igea", "Ignazio", "Igor", "Ilaria", "Ilario",
			"Ilda", "Ilia", "Ilva", "Imera", "Immacolata", "Indro", "Inga", "Ingmar", "Ingrid",
			"Iolanda", "Iole", "Iorio", "Ippolita", "Ippolito", "Irene", "Iris", "Iride", "Irma",
			"Irvin", "Isabella", "Isaura", "Isidoro", "Isotta", "Italo", "Ivan", "Ivana", "Ivano",
			"Ivilla", "Ivo", "Izusa", "Jader", "Jael", "Jafar", "Jamil", "Janez", "Jaron",
			"Jasmine", "Jason", "Jemina", "Jessica", "Jin", "Jocelyn", "Joel", "Joelle", "Jonathan",
			"Kamar", "Keith", "Ken", "Kendra", "Kilian", "Kim", "Kira", "Kirk", "Lada", "Ladislao",
			"Lamberto", "Lancelot", "Lanfranco", "Lara", "Laura", "Lavinia", "Lea", "Leandro",
			"Leda", "Lee", "Leila", "Leo", "Leon", "Leonardo", "Leone", "Leonida", "Leopoldo",
			"Leslie", "Letizia", "Levi", "Levia", "Lia", "Liala", "Liana", "Licia", "Lidia",
			"Liliana", "Lilith", "Lilka", "Linda", "Linnea", "Lino", "Linus", "Liu'", "Liuba",
			"Livia", "Livio", "Lonella", "Lora", "Loredana", "Loreley", "Lorena", "Lorenza",
			"Lorenzo", "Lothar", "Luana", "Luca", "Luce", "Lucia", "Luciana", "Luciano", "Lucio",
			"Lucrezia", "Ludmilla", "Ludovica", "Ludovico", "Luigi", "Luigia", "Luminosa", "Luna",
			"Lupo", "Lynn", "Mabel", "Macha", "Maddalena", "Madonna", "Mafalda", "Magnolia",
			"Mahina", "Maia", "Mainard", "Malcom", "Malik", "Malka", "Malvina", "Mammola",
			"Mandisa", "Manfredo", "Manlio", "Mara", "Marcella", "Marcello", "Marco", "Margherita",
			"Maria", "Marianna", "Nariano", "Marica", "Marilena", "Marilyn", "Marina", "Marino",
			"Mario", "Marlon", "Marlow", "Marta", "Martina", "Martino", "Marvin", "Marzia",
			"Marzio", "Massimiliano", "Massimo", "Matilde", "Matteo", "Mattia", "Maude", "Maura",
			"Maurizia", "Maurizio", "Mauro", "Medardo", "Medea", "Medusa", "Megan", "Melania",
			"Melantha", "Melba", "Melia", "Melinda", "Melissa", "Melody", "Melvin", "Mercedes",
			"Meredith", "Michela", "Michele", "Mildred", "Milena", "Milo", "Milton", "Milva",
			"Mimosa", "Mintha", "Miranda", "Mirina", "Mirinna", "Mirko", "Mirra", "Mirta", "Mizar",
			"Moanna", "Modesto", "Moira", "Momo", "Monica", "Morana", "Morena", "Moreno", "Morgan",
			"Morgana", "Mughetta", "Muriel", "Musa", "Nadia", "Naomi", "Nara", "Narilla", "Nasya",
			"Natale", "Natalia", "Nathaniel", "Nausicaa", "Nazario", "Neda", "Nella", "Nelson",
			"Nem", "Nereo", "Nerina", "Nicola", "Nicoletta", "Ninfa", "Nissa", "Nives", "Noa",
			"Noemi", "Nolan", "Nora", "Norberto", "Norma", "Norman", "Novella", "Nuriel", "Odell",
			"Odessa", "Odilia", "Ofelia", "Olaf", "Olga", "Oliana", "Olimpia", "Olisa", "Oliva",
			"Oliviero", "Omar", "Ombretta", "Ondina", "Onella", "Opal", "Orazio", "Orchidea",
			"Oreste", "Oriana", "Orio", "Orion", "Orlando", "Orlena", "Ornella", "Orso", "Orsola",
			"Ortensia", "Oscar", "Ossian", "Osvaldo", "Ottavia", "Ottaviano", "Ottavio", "Otto",
			"Ottone", "Owen", "Palma", "Palmira", "Paloma", "Pamela", "Pandia", "Pandora", "Paola",
			"Paolo", "Paralda", "Paride", "Pasquale", "Patrizia", "Patrizio", "Penelope",
			"Perceval", "Perla", "Perseo", "Pervinca", "Petronilla", "Petunia", "Pia", "Pico",
			"Piera", "Pietro", "Pio", "Pirro", "Pisana", "Polissena", "Porthos", "Porzia",
			"Preziosa", "Primavera", "Primo", "Primula", "Prisca", "Prisco", "Publio", "Querida",
			"Quincy", "Quintiliano", "Quinto", "Quinzio", "Quirino", "Rachele", "Raffaele",
			"Raffaella", "Rahda", "Raimonda", "Raimondo", "Reagan", "Rebecca", "Reed", "Regina",
			"Remigio", "Remo", "Renata", "Renato", "Rex", "Rhea", "Rhoda", "Rhys", "Riccarda",
			"Riccardo", "Rihanna", "Rinaldo", "Rita", "Roberta", "Roberto", "Robin", "Rocco",
			"Rodolfo", "Rodrigo", "Rohana", "Rok", "Rolf", "Romana", "Romano", "Romeo", "Romilda",
			"Romina", "Romolo", "Rooney", "Rosa", "Rosalia", "Rosalinda", "Rosaria", "Rosario",
			"Rosaura", "Ross", "Rossana", "Rossella", "Roswita", "Rowena", "Ruben", "Rubina",
			"Ruggero", "Ruth", "Ryan", "Sabra", "Sabrina", "Sada", "Sadir", "Sakura", "Salomu'",
			"Salomone", "Salvatore", "Samantha", "Samuele", "Santina", "Santino", "Sara", "Sarad",
			"Satinka", "Saul", "Saverio", "Savino", "Scilla", "Scott", "Sean", "Sebastiano",
			"Selene", "Selma", "Selvaggia", "Sem", "Sennen", "Senta", "Serafina", "Serafino",
			"Serena", "Sergio ", "Severo", "Shada", "Shaina", "Shanti", "Sharar", "Sharon",
			"Shaula", "Sheena", "Sheila", "Shirah", "Shirley", "Sibilla", "Sidney", "Sigfrido",
			"Sigmund", "Silvana", "Silvano", "Silvestro", "Silvia", "Simeone", "Simona", "Simone",
			"Sina", "Sirena", "Siro", "Sivio", "Skip", "Smeralda", "Sofia", "Solana", "Solange",
			"Soledad", "Sonia", "Spartaco", "Speranza", "Stanislao", "Stefania", "Stefano",
			"Stelio", "Stella", "Sulayman", "Sunna", "Susanna", "Sven", "Svetlana", "Taffy",
			"Takara", "Talia", "Talitha", "Tamara", "Tancredi", "Tara", "Taras", "Tarcisio",
			"Tatiana", "Tazio", "Tea", "Telga", "Teo", "Teodora", "Teodoro", "Terenzio", "Teresa",
			"Teseo", "Tessa", "Thelma", "Thera", "Tia", "Tiberio", "Tiffany", "Timoteo", "Titania", "Tito",
			"Tiziana", "Tiziano", "Tobia", "Tommaso", "Tosca", "Tristano", "Tullia", "Tullio",
			"Tyler", "Tyron", "Tyson", "Ubaldo", "Uberto", "Ugo", "Ulderico", "Uliana", "Ulisse",
			"Ulla", "Umberta", "Umberto", "Urania", "Uriel", "Ursula", "Valentina", "Valentino",
			"Valeria", "Valerio", "Vanessa", "Vasco", "Vassjli", "Vedia", "Vega", "Velania",
			"Velia", "Vera", "Verbena", "Verena", "Verilla", "Veronica", "Vesta", "Vida", "Videmar",
			"Vincenza", "Vincenzo", "Viola", "Virgilio", "Virginia", "Virginio", "Viridiana",
			"Vissia", "Vito", "Vittore", "Vittoria", "Vittorio", "Viviana", "Vladimiro", "Wala",
			"Waldo", "Wally", "Wanda", "Werner", "Werther", "Wilson", "Wolfgang", "Wolfram",
			"Xantha", "Xenia", "Ximena", "Xena", "Yama", "Yarin", "Yasu", "Ymer", "Ymir", "Yuma",
			"Yuri", "Yvonne", "Yumi", "Zada", "Zahara", "Zaira", "Zak", "Zarah", "Zelia", "Zelig",
			"Zenaide", "Zeno", "Zilla", "Zita", "Zoe", "Zorya", "Zuleika", "Zelda" };

	public static final String[] COGNOMI = { "Abbate", "Abbondanza", "Abu", "Accadia", "Acquafredda",
			"Acquafondata", "Acunzo", "Adorno", "Agostini", "Aguila", "Ahamed", "Ahmed El Ghandor",
			"Aiello", "Alam", "Albanese", "Albanese", "Alfano", "Alpi", "Amato", "Amato",
			"Andronico", "Andruccioli", "Angelicchio", "Angiuli", "Anklin", "Antonelli",
			"Antonelli", "Antosh", "Apa", "Apreda", "Arena", "Arlati", "Armaroli", "Assal",
			"Attendoli", "Avello", "Avendato", "Azzarri", "Bagnaia", "Bagnato", "Baiano", "Baldari",
			"Baldi", "Baldinotti", "Balice", "Balloni", "Balta", "Baragliu", "Barbieri", "Bardi",
			"Barone", "Barone", "Baronti", "Barruga", "Barsanti", "Bartolini", "Bartolucci",
			"Basile", "Basile", "Bassani", "Bassano", "Bassolino", "Battaglia", "Battelli",
			"Bazhanova", "Bazzocchi", "Bellaneve", "Bellettini", "Bellini", "Bellino", "Bellinzoni",
			"Bello", "Bencivenga", "Benedetti", "Benhadda", "Bennada Epse Herichi", "Bentivegna",
			"Bento Da Silva", "Berardi", "Bernacci", "Bernardi", "Bernardini", "Bertini",
			"Bevilacqua", "Bianchi", "Bianchi", "Bianco", "Biondini", "Blasi", "Blasi ", "Boes",
			"Boncompagni", "Bonn", "Bonomo", "Bonsignore", "Bonventre", "Borgat-wohlbang",
			"Borghini", "Borkowska", "Borrelli", "Boschi", "Botnariu", "Boubaker", "Bragioto",
			"Brambilla", "Brizi", "Brunetti", "Bruni", "Bruni", "Bruno", "Buccolieri", "Bugli",
			"Buongrazio", "Burla", "Bushulli", "Caccamo", "Cagnotti", "Calabrese", "Caldironi",
			"Caligari", "Caligiuri", "Callegarini", "Campana", "Campanella", "Cangini",
			"Canichella", "Caniglia ", "Cannizzaro", "Capanna", "Capelli", "Capitani", "Capone ",
			"Caporilli", "Caputo", "Caraballo", "Carbone", "Cardinetti", "Carina", "Carpi Marasco",
			"Carrara", "Carucci", "Carullo", "Caruso", "Casadei", "Casali", "Casella", "Castagna",
			"Castagnoli", "Castaldi", "Castaldo", "Castelli", "Catalano", "Cataldi", "Cattaneo",
			"Cauteruccio", "Cavallo", "Cavaterra", "Ceccarelli", "Ceccaroni", "Cecchetti", "Cecere",
			"Cellini", "Celotti", "Cenciarelli", "Ceraldi", "Cerchierini", "Cerilli", "Chaibi",
			"Charaf", "Cheikh Talibouya", "Chesti", "Chiricozzi", "Ciampaglia", "Ciarla",
			"Ciarlariello", "Cicconi", "Cichon", "Ciervo", "Cipollone", "Cirillo", "Clementucci",
			"Clesceri", "Coccia", "Colle", "Colli", "Colombo", "Colombo ", "Colongi", "Colonna",
			"Coluccia", "Coluccio", "Comini", "Conflitti", "Conte", "Conte", "Conti", "Contiu",
			"Coppola", "Corrado", "Corraretti", "Corrias", "Cospito", "Costa", "Costa",
			"Costantini", "Costantini", "Coulier", "Covato", "Cozzolino", "Crepaldi", "Croce",
			"Crognale", "Curcio", "Cusin", "Cutillo", "D'Achille", "D'Agapito", "D'Alessandro",
			"Dallago", "D'Ambrosio", "D'Amico", "D'Amora", "D'Amore", "De Angelis", "De Bacco",
			"De Cataldo", "De Domenico ", "De Filippis", "De Florio", "De Freitas Sousa Tavares",
			"De La Cruz", "De Luca", "De Matteo", "De Peppe", "De Rosa", "De Santis", "De Santis",
			"De Simone", "De Stefano", "De Sterlich", "Deiana", "Del Aguila Rosario",
			"Delgadillo Vargas", "Delgado", "D'emilia", "Di Benimeo", "Di Carlo", "Di Lena",
			"Di Maio", "Di Marco", "Di Mario", "Di Menna", "Di Paolo", "Di Pasquale", "Di Renna",
			"Di Ruzza", "Di Santo", "Di Sipio", "Di Stefano", "Di Tuoro ", "Diacetti", "Diamantini",
			"Disabato", "Dolciotti", "Domenicali", "Donatantonio", "Donati", "Donati", "Donatini",
			"Donnhauser", "Dorascenzi", "D'ottavio ", "Dotti", "Ducci", "Eichenberger", "El Falaki",
			"El Hallaf", "El Haqaoui", "El Kaaba  Armit", "Emili", "Emumwen", "Ercolani", "Ermeti",
			"Errahmani", "Errichetti", "Esposito", "Esposito", "Fabbri", "Fabbrizi", "Fabiani",
			"Fadda", "Farazi", "Farina", "Fasano", "Fassbender", "Fazi", "Felici", "Ferrante",
			"Ferrara", "Ferrarese", "Ferrari", "Ferrari", "Ferraro", "Ferrero", "Ferretti", "Ferri",
			"Ferro", "Fiadone ", "Fico", "Filagna", "Filipek", "Filippelli", "Filippi", "Finiti",
			"Fiordigigli", "Fiore", "Fiumi", "Fiuzzi", "Focaccia", "Fontana", "Fontana",
			"Fontanella", "Fontanilla", "Fontolan", "Forcina", "Forcina ", "Fortini", "Fossaroli",
			"Fralassi", "Franco", "Frasca", "Fraticelli", "Fratini", "Freschi ", "Fumagalli",
			"Fusco", "Fusini", "Gagliardi", "Galli", "Galli", "Gallo", "Galotti", "Gamberini",
			"Gargiulo", "Garofalo", "Gasmi", "Gatti", "Gatti", "Gealapu", "Gentile", "Gentili",
			"Gentilini", "Ghazi", "Ghini", "Giannetti", "Gigante", "Gindre", "Giordano",
			"Giorgetti", "Giorgi", "Giorgio", "Giuliani", "Giuliani", "Giura", "Giurgola", "Gnani",
			"Gori", "Graffiedi", "Grande", "Grassi", "Grasso", "Grebenea", "Greco", "Grimaldi",
			"Gromala", "Grossi Pavia", "Guaman", "Gubinelli", "Guerra", "Guida", "Guidi", "Guidi",
			"Guillen Crespo", "Gutjahr", "Guzman Soriano", "Haji", "Hajji", "Harasymiuk", "Harroud",
			"Haryadi", "Hijjoui", "Hossain", "Huaman Lopez", "Hushchyna", "Iachini", "Iacoangeli",
			"Iacobelli", "Ianne", "Iatalese", "Infante", "Iuliano", "Jagmin", "Jaschke ", "Jebrane",
			"Jianu", "Kamal", "Karim", "Kazi", "Kellmann", "Kosek", "Kovacs", "La Bella",
			"La Sorda", "Labella", "Lacerenza", "Laita", "Lanconelli", "Lanzoni", "Latini",
			"Lattanzi", "Laurenti", "Lazar", "Lazazzera", "Lecca", "Lelli", "Lena", "Leone",
			"Leonetti", "Lesniewska", "Liberto ", "Linzi", "Lippi", "Lombardi", "Lombardo", "Longo",
			"Lopez", "Lorusso", "Lucani", "Lucarini", "Lucchesini", "Lucchi", "Lunerti", "Luzietti",
			"Luzzi", "Magalotti", "Mahu", "Malagigi", "Maldini", "Mamone", "Manchia", "Mancini",
			"Mane", "Mane'", "Mangano", "Manzi", "Marano", "Marata", "Marchesini", "Marchetti",
			"Marchi", "Marchi", "Mariani", "Mariani", "Marini", "Marino", "Marocchini",
			"Maroncelli", "Marra", "Martellini ", "Martinelli", "Martini", "Martino", "Martino",
			"Martys", "Mascali Zeo", "Masetti", "Massa", "Mathlouthi", "Mattioni", "Mauro", "Mazza",
			"Medda", "Mele", "Meloni", "Mena", "Mercantini", "Messina", "Metozzi", "Meucci",
			"Mezzogori", "Michilli", "Milani", "Milenov", "Milutinovic", "Mincuzzi", "Minelli",
			"Minestrini ", "Minnella", "Minuz", "Mirante", "Mohammed", "Moiano", "Mollica",
			"Monaco", "Monsone ", "Monsorno", "Montanari", "Montevecchi", "Monti", "Montuori",
			"Morelli", "Moretti", "Moro", "Morselli", "Morsiani", "Moschetti", "Moukrim", "Mucci",
			"Mugione", "Muratori", "Mussinelli", "Naci", "Napoli", "Napolitano", "Narducci", "Neri",
			"Niane", "Nicastro", "Nini", "Nizzi", "Nurul", "Nuti", "Odigwe", "Oliva", "Olivelli",
			"Olivieri", "Orlandi", "Orlando", "Ortu", "Ossati", "Pace", "Pacini", "Paduano",
			"Pagano", "Paglia", "Pal Ionut", "Palatano", "Palazzari", "Palma ", "Palmieri",
			"Palumbo", "Panchetti", "Panichi", "Panza", "Paolini", "Papaleo", "Paradisi", "Parini",
			"Parisi", "Parravani", "Pascale", "Pascucci", "Pasolini", "Pasquini", "Passitto",
			"Pastore", "Patruno", "Patwary", "Paul", "Pellegrini", "Pellegrino", "Pelliccia",
			"Pello'", "Pelo", "Pepe", "Pereira De Castro", "Perrone", "Petritoli", "Pezzuco", "Pia",
			"Piacentini", "Piani", "Piazza", "Piccoli", "Piccolo", "Piersanti", "Pierucci",
			"Pierucci ", "Piga", "Pinna", "Pinna", "Piras", "Piro", "Pisacane", "Placidi ",
			"Planta", "Poli", "Policarpo", "Polidori", "Polyzopoulos", "Pompili", "Pongetti",
			"Poni", "Popescu", "Popovici", "Porcu", "Porta", "Potalivo ", "Pozzi", "Pozzi",
			"Pracucci", "Prelati", "Proietti", "Pucciotti", "Pulsoni", "Quadalti Noferini",
			"Quadrini", "Quartarone", "Rainesi", "Ranfi", "Ranucci", "Raqabi", "Rebeccato",
			"Renzoni", "Renzulli", "Resende Azevedo", "Riboloni", "Ricci", "Ricci", "Ricciardi",
			"Ricciolino", "Rifilato", "Rimoldi", "Rinaldi", "Riva", "Rizzelli", "Rizzi", "Rizzo",
			"Robbio", "Rocchi", "Romagnoli ", "Romani Bergonzo", "Romano", "Romano", "Romeo",
			"Rosata", "Rosati", "Rosato", "Rossetti", "Rossi", "Rossi", "Rotella", "Rucci", "Rudel",
			"Ruggeri", "Ruggieri", "Ruggiero", "Russo", "Russo", "Saccone", "Sala", "Sala",
			"Salamone ", "Salvemini", "Salvini", "Sanges", "Sanna", "Sanna", "Santana Moscato",
			"Santini", "Santoro", "Santucci", "Sarpieri", "Sartori", "Sartori", "Sassetti", "Sassi",
			"Sasvari", "Satta", "Sbreni", "Scarale", "Scardone", "Scipioni", "Scotti", "Sebastiani",
			"Sementilli", "Sepe ", "Serban", "Seri", "Serra", "Sestito", "Settembrini", "Severi",
			"Sgrigna", "Siapian", "Silvestri", "Simonetti", "Simoni", "Sipio", "Siracusa",
			"Soldati", "Sorbalo", "Sorgentone", "Soro", "Sorrentino", "Sorrentino", "Spalletta",
			"Speziale", "Spoletini", "Sposato", "Stazzone", "Stefanovich", "Steffanina",
			"Steffenoni", "Stefoni", "Strazzanti", "Succi", "Tabane", "Taifi", "Tambini", "Tarani",
			"Tarnogrodzki", "Tarozzi", "Taurone", "Tazzari", "Teodorani", "Terracciano", "Testa", "Tiberi",
			"Tiglio", "Tioni", "Tiranno", "Tisba", "Toader", "Tomassi", "Torraca", "Toso",
			"Tosolini", "Totaro ", "Tranquilli", "Trasforini", "Trombino", "Tronconi", "Tufano",
			"Tulli", "Turci", "Urbini", "Urzo", "Usami", "Vaccaro", "Valbonesi", "Valdinosi",
			"Valente", "Valentini", "Valvano", "Vandenbulcke", "Vanni", "Vannozzi", "Vassura",
			"Vella", "Veneziani", "Veneziano", "Verastegui Pereyra", "Vidanalage", "Villa", "Villa",
			"Villani", "Vincenzi", "Vinciguerra", "Vitale", "Vitali", "Vitor", "Volpe", "Von Oppen",
			"Wally", "Wenz", "Wicher", "Williams", "Wilmer", "Wirth", "Wozniak", "Wozniczka",
			"Zaccaria", "Zak", "Zamberlan", "Zandoli", "Zanella", "Zanellati", "Zanelli", "Zanetti",
			"Zapalski", "Zaratti", "Zavalloni", "Zavoli", "Zecchini", "Zenina", "Zeolla", "Zepponi",
			"Zinnamosca", "Zito", "Zivkovic", "Zolea", "Zolnowski", "Zuccherelli", "Zurzolo" };

	public static final String[] LOCALI = { "Osteria", "Ristorante", "Pizzeria", "Trattoria",
			"Enoteca", "Agriturismo", "Locanda", "Rosticceria", "Tavola Calda", "Pub" };

	public static final String[] DUG = { "Accesso", "Allea", "Alinea", "Alzaia", "Androna",
			"Angiporto", "Arco", "Archivolto", "Arena", "Argine", "Bacino", "Baluardo", "Banchi",
			"Banchina", "BarbarA¬a", "Bastione", "Bastioni", "Belvedere", "Bivio", "Borgata",
			"Borgo", "Borgoloco", "Cal", "Calata", "Calle", "Calle Larga", "Calle Lunga",
			"Calle Stretta", "CallesA¨lla", "CallesA¨llo", "CallA©tta", "Campiello", "Campo", "Canale",
			"Cantone", "Capo Di Piazza", "Carraia", "Carrara", "Carrarone", "Carro", "Cascina",
			"Case Sparse", "Cavalcavia", "Cavone", "Chiasso", "Chiassetto", "Chiassuola",
			"Circonvallazione", "Circumvallazione", "Claustro", "Clivio", "Clivo", "Complanare",
			"ContrA ", "Contrada", "Corsetto", "Corsia", "Corso", "Corte", "Cortesela", "Corticella",
			"Cortile", "Cortile Privato", "Costa", "Crocicchio", "Crosa", "Cupa", "Cupa Vicinale",
			"Diramazione", "Discesa", "Distacco", "Emiciclo", "Erta", "Estramurale", "Fondaco",
			"Fondamenta", "Fondo", "Fossa", "Fossato", "Frazione", "Galleria", "Gradinata",
			"Gradini", "Gradoni", "Granviale", "Isola", "Larghetto", "Largo", "Laterale", "Lido",
			"Lista", "Litoranea", "LocalitA ", "Lungadige", "Lungarno", "Lungo", "Lungoadda",
			"Lungoargine", "Lungobisagno", "Lungo Brenta", "Lungobusento", "Lungocalore",
			"Lungo Castellano", "Lungocrati", "Lungocanale", "Lungocurone", "Lungodora",
			"Lungofiume", "Lungofoglia", "Lungofrigido", "Lungogesso", "Lungoisarco", "Lungoisonzo",
			"Lungolago", "Lungolario", "Lungolinea", "Lungoliri", "Lungomare", "Lungomazaro",
			"Lungomolo", "Lungonera", "Lungoparco", "Lungo Po", "Lungoporto", "Lungosabato",
			"Lungosile", "Lungostura", "Lungotalvera", "Lungotanaro", "Lungotevere", "Lungoticino",
			"Lungotorrente", "Lungotronto", "Lungovelino", "Masseria", "Merceria", "Molo", "Mura",
			"Murazzi Del Po", "Parallela", "Passaggio", "Passaggio Privato", "Passeggiata",
			"Passeggio", "Passo", "Passo Di Piazza", "Pendice", "Pendino", "Pendio", "Penninata",
			"Piaggia", "Piazza", "Piazza", "Piazza", "Piazza", "Piazza", "Piazza", "Piazza",
			"Piazza Inferiore", "Piazza Privata", "Piazzale", "Piazzetta", "Piazzetta Privata",
			"Piscina", "Ponte", "Portico", "Porto", "Prato", "Prolungamento", "Quadrato", "Raggio",
			"Ramo", "Rampa", "Rampa Privata", "Rampari", "Rampe", "Ratto", "Recinto", "Regione",
			"Rettifilo", "Regaste", "Riello", "Rione", "Rio", "Rio TerA ", "Ripa", "Riva", "Riviera",
			"RondA²", "Rotonda", "Rua", "Ruga", "Rugheta", "Sacca", "Sagrato", "Saia", "Salita",
			"Salita Inferiore", "Salita Superiore", "Salizada", "Scalea", "Scalette", "Scalinata",
			"Scalone", "Scesa", "Sdrucciolo", "Selciato", "Sentiero", "Slargo", "Sopportico",
			"Sotoportego", "Sottoportico", "Spalto", "Spiaggia", "Spianata", "Spiazzo", "Strada",
			"Strada Accorciatoia", "Strada Alzaia", "Strada Antica", "Strada Arginale",
			"Strada Bassa", "Strada Cantoniera", "Strada Carrareccia", "Strada Consolare",
			"Strada Consortile", "Strada Consorziale", "Strada Di Bonifica", "Strada Esterna",
			"Strada Inferiore", "Strada Intercomunale", "Strada Interna", "Strada Interpoderale",
			"Strada Litoranea", "Strada Militare", "Strada Nazionale", "Strada Panoramica",
			"Strada Pedonale", "Strada Perimetrale", "Strada Poderale", "Strada Privata",
			"Strada Provinciale", "Strada Regionale", "Strada Rotabile", "Strada Rurale",
			"Strada Traversante", "Strada Vicinale", "Stradale", "Stradella", "Stradello",
			"Stradetta", "Stradone", "Stradoncello", "Stretta", "Stretto", "Strettoia", "Strettola",
			"Svoto", "Supportico", "Terrazza", "Tondo", "Traversa", "Traversa Privata",
			"Traversale", "Trasversale", "Tratturo", "Trazzera", "Tresanda", "Tronco", "Vanella",
			"Vallone", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via",
			"Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via", "Via",
			"Via Accorciatoia", "Via Al Mare", "Via Alta", "Via Alzaia", "Via Antica",
			"Via Arginale", "Via Bassa", "Via Circolare", "Via Comunale", "Via Consolare",
			"Via Cupa", "Via Destra", "Via Erta", "Via Estramurale", "Via Inferiore",
			"Via Intercomunale", "Via Interna", "Via Laterale", "Via Lungomare", "Via Militare",
			"Via Nazionale", "Via Nuova", "Via Pedonale", "Via Privata", "Via Provinciale",
			"Via Regionale", "Via Rotabile", "Via Rurale", "Via Sinistra", "Via Stretta",
			"Via Superiore", "Via Trasversale", "Via Vecchia", "Via Vicinale", "Vial", "Viale",
			"Viale Lungomare", "Viale Privato", "Vialetto", "Vialone", "Vicinale", "Vicoletto",
			"Vicoletto Cieco", "Vicolo", "Vicolo Chiuso", "Vicolo Cieco", "Vico",
			"Vico Estramurale", "Vico Inferiore", "Vico Lungo", "Vico Nuovo", "Vico Privato",
			"Vico Rotto", "Vico Storto", "Vico Stretto", "Vico Superiore", "Viella", "Vietta",
			"Villaggio", "Viottolo", "Viuzza", "Viuzzo", "Vocabolo", "Volti", "Voltone" };

	public static final String[] NUMERI_ROMANI = {"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI", "XXII", "XXIII", "XXIV", "XXV", "XXVI", "XXVII", "XXVIII", "XXIX", "XXX", "XXXI", "XXXII", "XXXIII", "XXXIV", "XXXV", "XXXVI", "XXXVII", "XXXVIII", "XXXIX", "XL", "XLI", "XLII", "XLIII", "XLIV", "XLV", "XLVI", "XLVII", "XLVIII", "XLIX", "L", "LI", "LII", "LIII", "LIV", "LV", "LVI", "LVII", "LVIII", "LIX", "LX", "LXI", "LXII", "LXIII", "LXIV", "LXV", "LXVI", "LXVII", "LXVIII", "LXIX", "LXX", "LXXI", "LXXII", "LXXIII", "LXXIV", "LXXV", "LXXVI", "LXXVII", "LXXVIII", "LXXIX", "LXXX", "LXXXI", "LXXXII", "LXXXIII", "LXXXIV", "LXXXV", "LXXXVI", "LXXXVII", "LXXXVIII", "LXXXIX", "XC", "XCI", "XCII", "XCIII", "XCIV", "XCV", "XCVI", "XCVII", "XCVIII", "XCIX", "C", "CI", "CII", "CIII", "CIV", "CV", "CVI", "CVII", "CVIII", "CIX", "CX", "CXI", "CXII", "CXIII", "CXIV", "CXV", "CXVI", "CXVII", "CXVIII", "CXIX", "CXX", "CXXI", "CXXII", "CXXIII", "CXXIV", "CXXV", "CXXVI", "CXXVII", "CXXVIII", "CXXIX", "CXXX", "CXXXI", "CXXXII", "CXXXIII", "CXXXIV", "CXXXV", "CXXXVI", "CXXXVII", "CXXXVIII", "CXXXIX", "CXL", "CXLI", "CXLII", "CXLIII", "CXLIV", "CXLV", "CXLVI", "CXLVII", "CXLVIII", "CXLIX", "CL", "CLI", "CLII", "CLIII", "CLIV", "CLV", "CLVI", "CLVII", "CLVIII", "CLIX", "CLX", "CLXI", "CLXII", "CLXIII", "CLXIV", "CLXV", "CLXVI", "CLXVII", "CLXVIII", "CLXIX", "CLXX", "CLXXI", "CLXXII", "CLXXIII", "CLXXIV", "CLXXV", "CLXXVI", "CLXXVII", "CLXXVIII", "CLXXIX", "CLXXX", "CLXXXI", "CLXXXII", "CLXXXIII", "CLXXXIV", "CLXXXV", "CLXXXVI", "CLXXXVII", "CLXXXVIII", "CLXXXIX", "CXC", "CXCI", "CXCII", "CXCIII", "CXCIV", "CXCV", "CXCVI", "CXCVII", "CXCVIII", "CXCIX", "CC", "CCI", "CCII", "CCIII", "CCIV", "CCV", "CCVI", "CCVII", "CCVIII", "CCIX", "CCX", "CCXI", "CCXII", "CCXIII", "CCXIV", "CCXV", "CCXVI", "CCXVII", "CCXVIII", "CCXIX", "CCXX", "CCXXI", "CCXXII", "CCXXIII", "CCXXIV", "CCXXV", "CCXXVI", "CCXXVII", "CCXXVIII", "CCXXIX", "CCXXX", "CCXXXI", "CCXXXII", "CCXXXIII", "CCXXXIV", "CCXXXV", "CCXXXVI", "CCXXXVII", "CCXXXVIII", "CCXXXIX", "CCXL", "CCXLI", "CCXLII", "CCXLIII", "CCXLIV", "CCXLV", "CCXLVI", "CCXLVII", "CCXLVIII", "CCXLIX", "CCL", "CCLI", "CCLII", "CCLIII", "CCLIV", "CCLV", "CCLVI", "CCLVII", "CCLVIII", "CCLIX", "CCLX", "CCLXI", "CCLXII", "CCLXIII", "CCLXIV", "CCLXV", "CCLXVI", "CCLXVII", "CCLXVIII", "CCLXIX", "CCLXX", "CCLXXI", "CCLXXII", "CCLXXIII", "CCLXXIV", "CCLXXV", "CCLXXVI", "CCLXXVII", "CCLXXVIII", "CCLXXIX", "CCLXXX", "CCLXXXI", "CCLXXXII", "CCLXXXIII", "CCLXXXIV", "CCLXXXV", "CCLXXXVI", "CCLXXXVII", "CCLXXXVIII", "CCLXXXIX", "CCXC", "CCXCI", "CCXCII", "CCXCIII", "CCXCIV", "CCXCV", "CCXCVI", "CCXCVII", "CCXCVIII", "CCXCIX", "CCC", "CCCI", "CCCII", "CCCIII", "CCCIV", "CCCV", "CCCVI", "CCCVII", "CCCVIII", "CCCIX", "CCCX", "CCCXI", "CCCXII", "CCCXIII", "CCCXIV", "CCCXV", "CCCXVI", "CCCXVII", "CCCXVIII", "CCCXIX", "CCCXX", "CCCXXI", "CCCXXII", "CCCXXIII", "CCCXXIV", "CCCXXV", "CCCXXVI", "CCCXXVII", "CCCXXVIII", "CCCXXIX", "CCCXXX", "CCCXXXI", "CCCXXXII", "CCCXXXIII", "CCCXXXIV", "CCCXXXV", "CCCXXXVI", "CCCXXXVII", "CCCXXXVIII", "CCCXXXIX", "CCCXL", "CCCXLI", "CCCXLII", "CCCXLIII", "CCCXLIV", "CCCXLV", "CCCXLVI", "CCCXLVII", "CCCXLVIII", "CCCXLIX", "CCCL", "CCCLI", "CCCLII", "CCCLIII", "CCCLIV", "CCCLV", "CCCLVI", "CCCLVII", "CCCLVIII", "CCCLIX", "CCCLX", "CCCLXI", "CCCLXII", "CCCLXIII", "CCCLXIV", "CCCLXV", "CCCLXVI", "CCCLXVII", "CCCLXVIII", "CCCLXIX", "CCCLXX", "CCCLXXI", "CCCLXXII", "CCCLXXIII", "CCCLXXIV", "CCCLXXV", "CCCLXXVI", "CCCLXXVII", "CCCLXXVIII", "CCCLXXIX", "CCCLXXX", "CCCLXXXI", "CCCLXXXII", "CCCLXXXIII", "CCCLXXXIV", "CCCLXXXV", "CCCLXXXVI", "CCCLXXXVII", "CCCLXXXVIII", "CCCLXXXIX", "CCCXC", "CCCXCI", "CCCXCII", "CCCXCIII", "CCCXCIV", "CCCXCV", "CCCXCVI", "CCCXCVII", "CCCXCVIII", "CCCXCIX", "CD", "CDI", "CDII", "CDIII", "CDIV", "CDV", "CDVI", "CDVII", "CDVIII", "CDIX", "CDX", "CDXI", "CDXII", "CDXIII", "CDXIV", "CDXV", "CDXVI", "CDXVII", "CDXVIII", "CDXIX", "CDXX", "CDXXI", "CDXXII", "CDXXIII", "CDXXIV", "CDXXV", "CDXXVI", "CDXXVII", "CDXXVIII", "CDXXIX", "CDXXX", "CDXXXI", "CDXXXII", "CDXXXIII", "CDXXXIV", "CDXXXV", "CDXXXVI", "CDXXXVII", "CDXXXVIII", "CDXXXIX", "CDXL", "CDXLI", "CDXLII", "CDXLIII", "CDXLIV", "CDXLV", "CDXLVI", "CDXLVII", "CDXLVIII", "CDXLIX", "CDL", "CDLI", "CDLII", "CDLIII", "CDLIV", "CDLV", "CDLVI", "CDLVII", "CDLVIII", "CDLIX", "CDLX", "CDLXI", "CDLXII", "CDLXIII", "CDLXIV", "CDLXV", "CDLXVI", "CDLXVII", "CDLXVIII", "CDLXIX", "CDLXX", "CDLXXI", "CDLXXII", "CDLXXIII", "CDLXXIV", "CDLXXV", "CDLXXVI", "CDLXXVII", "CDLXXVIII", "CDLXXIX", "CDLXXX", "CDLXXXI", "CDLXXXII", "CDLXXXIII", "CDLXXXIV", "CDLXXXV", "CDLXXXVI", "CDLXXXVII", "CDLXXXVIII", "CDLXXXIX", "CDXC", "CDXCI", "CDXCII", "CDXCIII", "CDXCIV", "CDXCV", "CDXCVI", "CDXCVII", "CDXCVIII", "CDXCIX", "D", "DI", "DII", "DIII", "DIV", "DV", "DVI", "DVII", "DVIII", "DIX", "DX", "DXI", "DXII", "DXIII", "DXIV", "DXV", "DXVI", "DXVII", "DXVIII", "DXIX", "DXX", "DXXI", "DXXII", "DXXIII", "DXXIV", "DXXV", "DXXVI", "DXXVII", "DXXVIII", "DXXIX", "DXXX", "DXXXI", "DXXXII", "DXXXIII", "DXXXIV", "DXXXV", "DXXXVI", "DXXXVII", "DXXXVIII", "DXXXIX", "DXL", "DXLI", "DXLII", "DXLIII", "DXLIV", "DXLV", "DXLVI", "DXLVII", "DXLVIII", "DXLIX", "DL", "DLI", "DLII", "DLIII", "DLIV", "DLV", "DLVI", "DLVII", "DLVIII", "DLIX", "DLX", "DLXI", "DLXII", "DLXIII", "DLXIV", "DLXV", "DLXVI", "DLXVII", "DLXVIII", "DLXIX", "DLXX", "DLXXI", "DLXXII", "DLXXIII", "DLXXIV", "DLXXV", "DLXXVI", "DLXXVII", "DLXXVIII", "DLXXIX", "DLXXX", "DLXXXI", "DLXXXII", "DLXXXIII", "DLXXXIV", "DLXXXV", "DLXXXVI", "DLXXXVII", "DLXXXVIII", "DLXXXIX", "DXC", "DXCI", "DXCII", "DXCIII", "DXCIV", "DXCV", "DXCVI", "DXCVII", "DXCVIII", "DXCIX", "DC", "DCI", "DCII", "DCIII", "DCIV", "DCV", "DCVI", "DCVII", "DCVIII", "DCIX", "DCX", "DCXI", "DCXII", "DCXIII", "DCXIV", "DCXV", "DCXVI", "DCXVII", "DCXVIII", "DCXIX", "DCXX", "DCXXI", "DCXXII", "DCXXIII", "DCXXIV", "DCXXV", "DCXXVI", "DCXXVII", "DCXXVIII", "DCXXIX", "DCXXX", "DCXXXI", "DCXXXII", "DCXXXIII", "DCXXXIV", "DCXXXV", "DCXXXVI", "DCXXXVII", "DCXXXVIII", "DCXXXIX", "DCXL", "DCXLI", "DCXLII", "DCXLIII", "DCXLIV", "DCXLV", "DCXLVI", "DCXLVII", "DCXLVIII", "DCXLIX", "DCL", "DCLI", "DCLII", "DCLIII", "DCLIV", "DCLV", "DCLVI", "DCLVII", "DCLVIII", "DCLIX", "DCLX", "DCLXI", "DCLXII", "DCLXIII", "DCLXIV", "DCLXV", "DCLXVI", "DCLXVII", "DCLXVIII", "DCLXIX", "DCLXX", "DCLXXI", "DCLXXII", "DCLXXIII", "DCLXXIV", "DCLXXV", "DCLXXVI", "DCLXXVII", "DCLXXVIII", "DCLXXIX", "DCLXXX", "DCLXXXI", "DCLXXXII", "DCLXXXIII", "DCLXXXIV", "DCLXXXV", "DCLXXXVI", "DCLXXXVII", "DCLXXXVIII", "DCLXXXIX", "DCXC", "DCXCI", "DCXCII", "DCXCIII", "DCXCIV", "DCXCV", "DCXCVI", "DCXCVII", "DCXCVIII", "DCXCIX", "DCC", "DCCI", "DCCII", "DCCIII", "DCCIV", "DCCV", "DCCVI", "DCCVII", "DCCVIII", "DCCIX", "DCCX", "DCCXI", "DCCXII", "DCCXIII", "DCCXIV", "DCCXV", "DCCXVI", "DCCXVII", "DCCXVIII", "DCCXIX", "DCCXX", "DCCXXI", "DCCXXII", "DCCXXIII", "DCCXXIV", "DCCXXV", "DCCXXVI", "DCCXXVII", "DCCXXVIII", "DCCXXIX", "DCCXXX", "DCCXXXI", "DCCXXXII", "DCCXXXIII", "DCCXXXIV", "DCCXXXV", "DCCXXXVI", "DCCXXXVII", "DCCXXXVIII", "DCCXXXIX", "DCCXL", "DCCXLI", "DCCXLII", "DCCXLIII", "DCCXLIV", "DCCXLV", "DCCXLVI", "DCCXLVII", "DCCXLVIII", "DCCXLIX", "DCCL", "DCCLI", "DCCLII", "DCCLIII", "DCCLIV", "DCCLV", "DCCLVI", "DCCLVII", "DCCLVIII", "DCCLIX", "DCCLX", "DCCLXI", "DCCLXII", "DCCLXIII", "DCCLXIV", "DCCLXV", "DCCLXVI", "DCCLXVII", "DCCLXVIII", "DCCLXIX", "DCCLXX", "DCCLXXI", "DCCLXXII", "DCCLXXIII", "DCCLXXIV", "DCCLXXV", "DCCLXXVI", "DCCLXXVII", "DCCLXXVIII", "DCCLXXIX", "DCCLXXX", "DCCLXXXI", "DCCLXXXII", "DCCLXXXIII", "DCCLXXXIV", "DCCLXXXV", "DCCLXXXVI", "DCCLXXXVII", "DCCLXXXVIII", "DCCLXXXIX", "DCCXC", "DCCXCI", "DCCXCII", "DCCXCIII", "DCCXCIV", "DCCXCV", "DCCXCVI", "DCCXCVII", "DCCXCVIII", "DCCXCIX", "DCCC", "DCCCI", "DCCCII", "DCCCIII", "DCCCIV", "DCCCV", "DCCCVI", "DCCCVII", "DCCCVIII", "DCCCIX", "DCCCX", "DCCCXI", "DCCCXII", "DCCCXIII", "DCCCXIV", "DCCCXV", "DCCCXVI", "DCCCXVII", "DCCCXVIII", "DCCCXIX", "DCCCXX", "DCCCXXI", "DCCCXXII", "DCCCXXIII", "DCCCXXIV", "DCCCXXV", "DCCCXXVI", "DCCCXXVII", "DCCCXXVIII", "DCCCXXIX", "DCCCXXX", "DCCCXXXI", "DCCCXXXII", "DCCCXXXIII", "DCCCXXXIV", "DCCCXXXV", "DCCCXXXVI", "DCCCXXXVII", "DCCCXXXVIII", "DCCCXXXIX", "DCCCXL", "DCCCXLI", "DCCCXLII", "DCCCXLIII", "DCCCXLIV", "DCCCXLV", "DCCCXLVI", "DCCCXLVII", "DCCCXLVIII", "DCCCXLIX", "DCCCL", "DCCCLI", "DCCCLII", "DCCCLIII", "DCCCLIV", "DCCCLV", "DCCCLVI", "DCCCLVII", "DCCCLVIII", "DCCCLIX", "DCCCLX", "DCCCLXI", "DCCCLXII", "DCCCLXIII", "DCCCLXIV", "DCCCLXV", "DCCCLXVI", "DCCCLXVII", "DCCCLXVIII", "DCCCLXIX", "DCCCLXX", "DCCCLXXI", "DCCCLXXII", "DCCCLXXIII", "DCCCLXXIV", "DCCCLXXV", "DCCCLXXVI", "DCCCLXXVII", "DCCCLXXVIII", "DCCCLXXIX", "DCCCLXXX", "DCCCLXXXI", "DCCCLXXXII", "DCCCLXXXIII", "DCCCLXXXIV", "DCCCLXXXV", "DCCCLXXXVI", "DCCCLXXXVII", "DCCCLXXXVIII", "DCCCLXXXIX", "DCCCXC", "DCCCXCI", "DCCCXCII", "DCCCXCIII", "DCCCXCIV", "DCCCXCV", "DCCCXCVI", "DCCCXCVII", "DCCCXCVIII", "DCCCXCIX", "CM", "CMI", "CMII", "CMIII", "CMIV", "CMV", "CMVI", "CMVII", "CMVIII", "CMIX", "CMX", "CMXI", "CMXII", "CMXIII", "CMXIV", "CMXV", "CMXVI", "CMXVII", "CMXVIII", "CMXIX", "CMXX", "CMXXI", "CMXXII", "CMXXIII", "CMXXIV", "CMXXV", "CMXXVI", "CMXXVII", "CMXXVIII", "CMXXIX", "CMXXX", "CMXXXI", "CMXXXII", "CMXXXIII", "CMXXXIV", "CMXXXV", "CMXXXVI", "CMXXXVII", "CMXXXVIII", "CMXXXIX", "CMXL", "CMXLI", "CMXLII", "CMXLIII", "CMXLIV", "CMXLV", "CMXLVI", "CMXLVII", "CMXLVIII", "CMXLIX", "CML", "CMLI", "CMLII", "CMLIII", "CMLIV", "CMLV", "CMLVI", "CMLVII", "CMLVIII", "CMLIX", "CMLX", "CMLXI", "CMLXII", "CMLXIII", "CMLXIV", "CMLXV", "CMLXVI", "CMLXVII", "CMLXVIII", "CMLXIX", "CMLXX", "CMLXXI", "CMLXXII", "CMLXXIII", "CMLXXIV", "CMLXXV", "CMLXXVI", "CMLXXVII", "CMLXXVIII", "CMLXXIX", "CMLXXX", "CMLXXXI", "CMLXXXII", "CMLXXXIII", "CMLXXXIV", "CMLXXXV", "CMLXXXVI", "CMLXXXVII", "CMLXXXVIII", "CMLXXXIX", "CMXC", "CMXCI", "CMXCII", "CMXCIII", "CMXCIV", "CMXCV", "CMXCVI", "CMXCVII", "CMXCVIII", "CMXCIX", "M"};

	public static final String[] MENU = { "Menu' Bambini", "Menu' Vegetariano", "Menu' Vegano",
			"Menu' per Celiaci", "Menu' Famiglia", "Menu' di Carne", "Menu' di Pesce",
			"Menu' di Pasqua", "Menu' di Pasquetta", "Menu' di Ferragosto", "Menu' di Natale",
			"Menu' di Capodanno", "Menu' Gourmet", "Menu' Premium", "Menu' dello Chef",
			"Menu' Tradizionale", "Menu' della Tradizione", "Menu' della Casa", "Menu' del Giorno",
			"Menu' Casereccio", "McMenu'", "Menu' Convenienza", "Menu' Extra Large" };

	public static final String[] CATEGORIE_ECOMMERCE = { "Bellezza", "Salute", "Animali", "Casa",
			"Cucina", "Sport", "Tempo Libero", "Prima infanzia", "Cancelleria", "Fai da te",
			"Elettronica", "Giardinaggio", "Informatica", "Auto e Moto", "Abbigliamento", "Giochi",
			"Illuminazione", "Scarpe", "Borse", "Valigeria", "Gioielli", "Strumenti musicali",
			"Videogiochi", "Elettrodomestici", "Libri", "Orologi", "Idee Regalo",
			"Prodotti Alimentari", "Software", "Hardware", "Film e TV", "Giocattoli", "Bambini",
			"Prodotti per Ufficio", "CD e Vinili" };

	public static final String[] FAKE_WORDS = { "Papapay", "Cockshed", "Pitioning", "Terithrow",
			"Subgrated", "Allouncer", "Cended", "Payellards", "Moderock", "Catermich",
			"Stardestrious", "Irrublor", "Ricouncitant", "Impencured", "Thrubbish", "Dizoolexa",
			"Compto", "Talocajoling", "Tribution", "Gyshile", "Bashanks", "Miralitt",
			"Evenchically", "Eaterfully", "Jobfusticate", "Hygienevangelist", "Racted", "Brigate",
			"Muskely", "Preppanting", "Opcong", "Wetwest", "Ivortion", "Paratered", "Uliratha",
			"Ovistshing", "Joristic", "Grob", "Steredects", "Gioppler", "Stally", "Replitz",
			"Corrower", "Eminste", "Matumbia", "Oleald", "Maxteep", "Branizericing", "Gebreakank",
			"Flaudient", "Delistemanally", "Senhamperking", "Cleviationly", "Parapentors",
			"Firehorse", "Litated", "Obstans", "Eminste", "Recinators", "Azzimpler", "Ezocholon",
			"Mahardston", "Cliple", "Catermich", "Huzlip", "Trates", "Reveforly", "Infusidicienes",
			"Vacarestracian", "Grapdrow", "Attelling", "Parkasting", "Imartankhang", "Republast",
			"Veytoy", "Beaspieching", "Blonneymon", "Enfinizatics", "Hattitude", "Ratica",
			"Eklimmsel", "Utionsons", "Sastery", "Satinge", "Peloozoid", "Mentrition", "Nalpure",
			"Corrot", "Sagending", "Sedubing", "Monikorasort", "Hioffpo", "Finatitaing", "Vabling",
			"Milateramilt", "Variskys", "Hughte", "Nekmit", "Moducilwoops", "Cippert", "Redully",
			"Fuppeto", "Whipletener", "Houshia", "Boilest", "Drywest", "Syricouch", "Prologisang",
			"Incircers", "Oppoons", "Reachrigy", "Cikliption", "Vansion", "Ropouts",
			"Regalawsuisted", "Lochich", "Animepolis", "Pullmaplic", "Occlon", "Happliest",
			"Roshankleboal", "Logingindecars", "Cleoniclosel", "Mingstrity", "Overudes",
			"Inefulnessalle", "Weisatted", "Fruismyther", "Delistemanally", "Ettiquartz", "Donsul",
			"Cippert", "Hysleria", "Impenelly", "Inusintering", "Untypistown", "Choorlish",
			"Numentursofaus", "Obsenators", "Breater", "Cusing", "Subtrattagons", "Crucate",
			"Noelind", "Matigulating", "Sneablathes", "Posistorather", "Expets", "Roinad",
			"Queudoted", "Novanoid", "Nekmit", "Yeinydd", "Hysleria", "Hooppler", "Dropperclear",
			"Esuyp", "Nanoarrow", "Qiameth", "Alerrawia", "Pulappli", "Wetchop", "Frorealm",
			"Vacso", "Arrowgance", "Shiphile", "Gogogox", "Siopp", "Bestfloor", "Gogopo",
			"Busyglide", "Spourmo", "Yodacloud", "Fluffster", "Ociramma", "Skizzle", "Sevit",
			"Defas", "Looplab", "Doggax", "Qerrassa", "Nalpure", "Shorogyt", "Zestpond", "Naperone",
			"Noxu", "Hexteria", "Eggmode", "Chucknology", "Bistup", "Sinpad", "Reiltas",
			"Steeplump", "Kizerain", "Spusious", "Lotadilo", "Swooflia", "Bronea", "Hawkloon",
			"Kiraric", "Parede", "Besloor", "Wavefire", "Glomtom", "Aferraron", "Tupacase",
			"Didiza", "Chershoee", "Onama", "Biasdo", "Boxscape", "Seiliu", "Chorenn", "Wetwest",
			"Novaly", "Werradith", "Hoppler", "Eraow", "Acaer", "Yoffa", "Jeren", "Tupress",
			"Animepolis", "Noelind", "Ekcle", "Hendassa", "Glaretram", "Winooze", "Surogou",
			"Brewtine", "Chillaid", "Rodrup", "Toximble", "Morath", "Nocobot", "Digikiki", "Oleald",
			"Yimello", "Voquev", "Resaix", "Peachflame", "Yboiveth", "Toogit", "Novanoid", "Nekmit",
			"Yeinydd", "Hysleria", "Hooppler", "Luezoid", "Chesture", "Feandra", "Boaclick",
			"Yammoe", "Mofoblitz", "Xanpon", "Singlewave", "Roplixoo", "Losenoid", "Loodon",
			"Rowlow", "Claster", "Pepelexa", "Sertave", "Dropellet", "Jeebus", "Noodile",
			"Drearien", "Kaloolon", "Norrisology", "Ybuwyn", "Fuffapster", "Jobox", "Creabird",
			"Astauand", "Mizuxe", "Slabdrill", "Zestybus", "Ferirama", "Tuttadit", "Printure",
			"Geosyog", "Plakill", "Bioyino", "Waratel", "Sexatoo", "Moderock", "Replitz", "Pegmode",
			"Mizule", "Lazap" };

	public static final String[] VCVCVCV = { "Orizefe", "Ubusepu", "Ifaguva", "Ozigefo", "Omutifa",
			"Afumudu", "Enepube", "Opanume", "Azodafi", "Ovepapu", "Ulomezu", "Asuvuce", "Agunemi",
			"Efurozu", "Emoveru", "Icebeti", "Isafupo", "Elacebo", "Agomasa", "Ogubisi", "Acecata",
			"Ebupone", "Omuvuco", "Odenezi", "Acotaru", "Ezamopi", "Agovanu", "Ofafuba", "Enebaga",
			"Irurora", "Avevami", "Amamuco", "Osoposu", "Adolufe", "Erofano", "Ifupeso", "Ecomuvi",
			"Azupupa", "Efivide", "Idefese", "Ilafesa", "Izimume", "Ezupuso", "Amerize", "Adocego",
			"Agavasi", "Ulamevu", "Isepeva", "Upepedi", "Unonavo", "Esumilu", "Avesote", "Esufegu",
			"Ogepabi", "Erufelo", "Usatede", "Onalora", "Afitaso", "Ebipibe", "Ovivubi", "Acimoso",
			"Imerona", "Ezogafi", "Ivezise", "Itufemu", "Avedofu", "Aciliro", "Amibeba", "Arevodo",
			"Efuficu", "Ifeveva", "Ofonavi", "Edapucu", "Omenepu", "Igasano", "Itupamu", "Avezodi",
			"Afifada", "Uzogeze", "Emuponu", "Unineru", "Elotule", "Alarumu", "Emelezu", "Epenefa",
			"Amogoca", "Ucuzoce", "Abomodo", "Emobela", "Edusure", "Odidoda", "Omupulo", "Udiriti",
			"Opesocu", "Ezedele", "Ufibemo", "Ucuviga", "Ugadevi", "Onuboco", "Utilelo", "Ezasugi",
			"Amipibu", "Aburedi", "Olicosu", "Obetimi", "Uburufo", "Utobotu", "Evanavu", "Agozevu",
			"Evimizu", "Izirube", "Inafamo", "Igovoce", "Otigove", "Idilepa", "Icezubo", "Urozulu",
			"Abunoge", "Acunofa", "Enifode", "Apamete", "Umevidi", "Ifunugo", "Ilulilu", "Alucudu",
			"Uculero", "Esamelu", "Anavuro", "Olemaza", "Itimelu", "Ezecebo", "Ozabida", "Avusofa",
			"Ozarevu", "Avisefe", "Enesibo", "Esogube", "Analuda", "Ocemedu", "Amisovu", "Uforizo",
			"Ulalafo", "Ucumime", "Ugodolo", "Osoturi", "Ivomame", "Osobabo", "Iponage", "Ozevofo",
			"Olomenu", "Egovepo", "Evozoco", "Umesigo", "Ovelebo", "Udaporu", "Efusuzo", "Imurogi",
			"Ovoleba", "Onerabo", "Ovebetu", "Ubucobu", "Idesagi", "Eperesa", "Igarozu", "Obusopu",
			"Uvuloza", "Ocetovu", "Anusice", "Osacipo", "Itafudo", "Ocadire", "Onetiba", "Ametote",
			"Atutotu", "Ivipure", "Azevumu", "Umacuni", "Osiduce", "Azetiro", "Imepalu", "Itodeca",
			"Atitori", "Upocibe", "Onobipu", "Acadute", "Uladuve", "Ulifona", "Agisunu", "Iripide",
			"Etemata", "Uvusana", "Abafoso", "Abolofo", "Isumave", "Ifidozu", "Eruvuci", "Odulune",
			"Iposule", "Ibogucu", "Obavefe", "Ononuri", "Izafiga", "Afefiro", "Iremufu", "Apigetu",
			"Umugizo", "Unafide", "Ivufebi", "Enoveli", "Erofitu", "Utimami", "Esifapa", "Atalezu",
			"Osatiro", "Ivepuzu", "Avovilo", "Ezuveru", "Iramati", "Alizaca", "Osilimu", "Onuboni",
			"Osalomu", "Emosaca", "Omufuge", "Izabogo", "Ubovuto", "Ubezuzi", "Ozufalo", "Azefupo",
			"Obogove", "Amesega", "Elacega", "Elaciga", "Edinini", "Orumulo", "Osezunu", "Uguvopi",
			"Umunazu", "Obicobo", "Amunuco", "Ifanozo", "Umodecu", "Alevili", "Erumubi", "Ugecopo",
			"Ebusago", "Useguvo", "Uviriri", "Uluzeba", "Unomape", "Imuzila", "Irunuma", "Onapazu",
			"Eticadi", "Icocavu", "Imavogi", "Elotupo", "Atoneda", "Ofegalu", "Elazati", "Asucere",
			"Ozagapa", "Imuvise", "Inotifi", "Ogetize", "Igutida", "Odotape", "Otucepo", "Erudupe",
			"Epoletu", "Utesite", "Etapivo", "Ovilufe", "Abusazo", "Ovazivo", "Azovelo", "Avozeze",
			"Irosabo", "Ofisuru", "Ocipuda", "Apilazo", "Itafevo", "Ezuvimi", "Umadavo", "Ovafiba",
			"Edovove", "Aducule", "Ucapuco", "Idanevo", "Afobivo", "Ugitecu", "Ogecono", "Ofogonu",
			"Evutara", "Ebegize", "Enalari", "Icapuvu", "Asemape", "Erimaru", "Uzudoca", "Avedido",
			"Ipelevu", "Urufasu", "Ipetoba", "Analoze", "Umefeto", "Ibedafa", "Elenomu", "Agumaba",
			"Anapile", "Edinuca", "Ovividi", "Otivede", "Olivuru", "Ecaruri", "Anunogi", "Usofife",
			"Izemuro", "Ozatopi", "Agemuro", "Ifedise", "Uzubuva", "Ususalu", "Olevevi", "Etobiva",
			"Urapabi", "Itinafi", "Ufumopo", "Odibiza", "Orufufu", "Utabudi", "Icipori", "Oguleco",
			"Izebifi", "Atevogo", "Icavuge", "Apagagu", "Umebuni", "Anolaci", "Agogoda", "Osilobe",
			"Egafodu", "Upobeno", "Ifudonu", "Emuluzo", "Igovoza", "Ifinodi", "Otubera", "Iziguva",
			"Ucedovu", "Igocugu", "Ilazito", "Icabaro", "Otobalu", "Ilotube", "Ofitano", "Onoramo",
			"Uvamido", "Epofari", "Orabunu", "Emubuso", "Avazule", "Efezimu", "Urisumi", "Esinodo",
			"Agelalo", "Ivubebo", "Odisuta", "Alovage", "Uloboce", "Ecobose", "Umegefo", "Ogeluco",
			"Onezico", "Ipotobe" };

	public static final String[] CITTA = {"A Coruna", "Aachen", "Aarhus", "Abbeville", "Aberdeen (UK)", "Aberdeen (South Dakota)", "Aberdeen (Washington)", "Abilene", "Abu Dhabi", "Acapulco", "Adelaide", "Adelboden", "Agadir", "Agde", "Agen", "Agios Nikolaos", "Agrigento", "Agropoli", "Aigues-Mortes", "Aix-en-Provence", "Aix-les-Bains", "Ajaccio", "Ajman", "Akron", "Al Ain", "Alanya", "Albacete", "Albany", "Albenga", "Albi", "Albufeira", "Albuquerque", "Alcudia", "Alessandria", "A&#133;lesund", "Alexandria", "Algeciras", "Alghero", "Alicante", "Alkmaar", "Allentown", "Alpe d'Huez", "Alta Badia", "Altea", "Altoona", "Amalfi", "Amarillo", "Amersfoort", "Amiens", "Amsterdam", "Anaheim", "Anchorage", "Ancona", "Andalo", "Andermatt", "Andria", "Angers", "AngoulAŠme", "Ankara", "Ann Arbor", "Annapolis", "Annecy", "Antalya", "Antibes", "Antwerp", "Anzio", "Ao Nang", "Aosta", "Apeldoorn", "Appleton", "Aracaju", "Arcachon", "Arenzano", "Arezzo", "Argostoli", "Arica", "Arles", "Arlington (Virginia)", "Arlington (Texas)", "Armagh", "Arnhem", "Arosa", "Arras", "Arrecife", "ArtA ", "Asbury Park", "Ascoli Piceno", "Ascona", "Ashdod", "Ashkelon", "Aspen", "Asti", "Astoria", "Athens", "Athlone", "Atlanta", "Atlantic City", "Auckland", "Augsburg", "Augusta (Georgia)", "Augusta (Maine)", "Aurora (Colorado)", "Aurora (Illinois)", "Austin", "Auxerre", "Avalon (New Jersey)", "Avalon (California)", "Aveiro", "Avellino", "Avignon", "Avoriaz", "Axamer Lizum", "Ayia Napa", "", "Bad Gastein", "Bad Hofgastein", "Baden", "Baiona", "Bakersfield", "Baltimore", "Bandar Seri Begawan", "Bandol", "Bangkok", "Bangor", "Bar", "Bar Harbor", "Barcelona", "Bari", "Barletta", "Barstow", "Basel", "Bastia", "Bath", "Baton Rouge", "Batumi", "Bayonne", "Beaulieu-sur-Mer", "Beaumont", "Beaune", "Beersheba", "Beijing", "Beirut", "Belfast", "Belfort", "Belgrade", "Belize City", "Bellingham", "Bellinzona", "Belluno", "Belmopan", "Belo Horizonte", "Bemidji", "Benalmadena", "Bend", "Bendigo", "Benevento", "BenicA ssim", "Benidorm", "Bergamo", "Bergen", "Bergerac", "Berkeley", "Berlin", "Bern", "BesanA§on", "Bethlehem", "Beverly Hills", "Badziers", "Biarritz", "Biel/Bienne", "Bielefeld", "Biella", "Bilbao", "Billings", "Biloxi", "Birmingham (UK)", "Birmingham (U.S.)", "Bismarck", "Bissau", "Blanes", "Bled", "Blois", "Bloomington", "Blumenau", "Boca Chica", "Boca Raton", "Bochum", "Bodrum", "Boise", "Bologna", "Bolzano", "Bonifacio", "Bonn", "Bordeaux", "Bordighera", "Bormio", "Boston", "Boulder", "Boulogne-sur-Mer", "Bourges", "Bowling Green", "Boynton Beach", "Bozeman", "Bradenton", "Bradford", "Braga", "Brampton", "Brasilia", "Bratislava", "Braunschweig", "Breda", "Bregenz", "Brela", "Bremen", "Bremerhaven", "Brescia", "Brest", "Bridgeport", "Brighton", "Brindisi", "Brisbane", "Bristol", "Brixen", "Brixental", "Brno", "Brookings", "Brownsville", "Bruges", "Brussels", "Bucharest", "Budapest", "Budva", "Buenos Aires", "Buffalo", "Burgas", "Burlington", "Butte", "", "Cabo San Lucas", "CAAdiz", "Caen", "Cagliari", "Cagnes-sur-Mer", "Cairns", "Cala Bona", "Cala d'Or", "Cala Millor", "Cala Ratjada", "Calais", "Calella", "Calgary", "Caloundra", "Calp", "Caltanissetta", "Calvi", "Cambridge (UK)", "Cambridge (U.S.)", "Cambrils", "Camden", "Campinas", "Campobasso", "Can Picafort", "Canazei", "Canberra", "Cancun", "Cannes", "Cannon Beach", "Canterbury", "Canton", "Canyamel", "Capdepera", "Cape Canaveral", "Cape Coral", "Cape May", "Cape Town", "Carbonia", "Carcassonne", "Cardiff", "Carlisle", "Carlsbad", "Carmel-by-the-Sea", "Carpi", "Carpinteria", "Carrara", "Carson City", "Cartagena", "Casablanca", "Caserta", "Casper", "Cassis", "Castelrotto", "Catania", "Catanzaro", "Caxias do Sul", "Cedar Rapids", "Cervinia", "Cesena", "Ä&#140;eskA1/2 Krumlov", "A&#135;eÅ&#159;me", "Chamonix", "Chandler", "Chania", "Charleroi", "Charleston (West Virginia)", "Charleston (South Carolina)", "Charlotte", "Charlottetown", "Chartres", "Chattanooga", "Chelmsford", "Chemnitz", "Cherbourg", "Chesapeake", "Chester", "Cheyenne", "Chiang Mai", "Chiang Rai", "Chiavari", "Chicago", "Chichester", "Chieti", "Chincoteague", "Chioggia", "Chios", "Chonburi", "Christchurch", "Chula Vista", "Chur", "Cincinnati", "Ciutadella de Menorca", "Civitavecchia", "Clarksville", "Clearwater", "Clermont-Ferrand", "Cleveland", "Cocoa Beach", "Coconut Creek", "Coimbra", "Collioure", "Colmar", "Cologne", "Colorado Springs", "Columbia (South Carolina)", "Columbia (Missouri)", "Columbus", "Como", "ConcepciAģn", "Concord", "Conil de la Frontera", "Conway", "Copenhagen", "Coral Springs", "CAģrdoba (Argentina)", "CAģrdoba (Spain)", "Corfu", "Corinth", "Cork", "Corpus Christi", "Corralejo", "Cortina d'Ampezzo", "Cosenza", "Costa Adeje", "Courchevel", "Courmayeur", "Coventry", "Covington", "Coyhaique", "Cozumel", "Crans-Montana", "Cremona", "Crotone", "Cuneo", "", "Da Nang", "Dakar", "Dallas", "Dana Point", "Darmstadt", "Darwin", "Daugavpils", "Dauphin Island", "Davenport", "Davos", "Dayton", "Daytona Beach", "Deauville", "Decatur", "Deerfield Beach", "Del Mar", "Delft", "Delray Beach", "Den Bosch", "Denia", "Denton", "Denver", "Derby", "Derry", "Des Moines", "Detroit", "Didim", "Dieppe", "Dijon", "Doha", "Dolomiti Superski", "Dordrecht", "Dorfgastein", "Dortmund", "Dothan", "Dover (Delaware)", "Dover (New Hampshire)", "Dresden", "Dubai", "Dublin", "Dubrovnik", "Duisburg", "Duluth", "Dundalk", "Dundee", "Dunedin", "Dunkirk", "Durham (UK)", "Durham (U.S.)", "DAžsseldorf", "", "Eastbourne", "Eau Claire", "Edgartown", "Edinburgh", "Edmonton", "Eilat", "Eindhoven", "El Paso", "Elche", "Elizabeth", "Elko", "Ellmau", "Elm", "Empuriabrava", "Encinitas", "Engelberg", "Enna", "Enschede", "A&#137;pinal", "Erfurt", "Erie", "Erlangen", "Esbjerg", "Espace Killy", "Essaouira", "Essen", "Estepona", "Eugene", "Eureka", "Evansville", "Everett", "Exeter", "A&#136;ze", "", "Faenza", "Fairbanks", "Falmouth", "Famagusta", "Fano", "Fargo", "Faro", "Fayetteville (North Carolina)", "Fayetteville (Arkansas)", "Fermo", "Fernandina Beach", "Ferrara", "Fethiye", "Fez", "Fieberbrunn", "Filzmoos", "Finale Ligure", "Fiumicino", "Flagstaff", "Flaine", "Flint", "Florence", "Florence (Alabama)", "Foggia", "Folgarida", "Fontana", "ForlAŽ", "Fort Collins", "Fort Lauderdale", "Fort Myers", "Fort Smith", "Fort Wayne", "Fort Worth", "Forte dei Marmi", "Foz do IguaA§u", "Frankfort", "Frankfurt am Main", "Franklin", "Frederick", "Fredericton", "Freeport", "Freiburg", "Fremont", "Fresno", "Fribourg", "Frosinone", "Fuengirola", "Fujairah", "Fukuoka", "Funchal", "Gainesville", "GaltAžr", "Galway", "Garden Grove", "Garland", "Gastonia", "Gatineau", "Gdansk", "Gdynia", "Geelong", "Gelsenkirchen", "Geneva", "Genoa", "George Town", "Ghent", "GijAģn", "Gilbert", "Girona", "Glasgow", "Glendale (Arizona)", "Glendale (California)", "Gloucester", "Gold Coast", "Gorizia", "Dachstein-West", "Gothenburg", "GAķttingen", "Gouda", "Granada", "Grand Forks", "Grand Island", "Grand Junction", "Grand Prairie", "Grand Rapids", "Granville", "Grasse", "Graz", "Great Falls", "Greeley", "Green Bay", "Greensboro", "Greenville NC", "Greenville SC", "Grenoble", "Grindelwald", "Groningen", "Grossarl", "Grosseto", "Gstaad", "Guadalajara", "Guangzhou", "GuimarAĢes", "Gulf Shores", "Gulfport", "", "Haarlem", "Haifa", "Halifax", "Halle", "Hamburg", "Hamilton (Canada)", "Hamilton (New Zealand)", "Hampton", "Hanford", "Hangzhou", "Hannover", "Hanoi", "Harrisburg", "Hartford", "Hasselt", "Hastings", "Hat Yai", "Hattiesburg", "Havana", "Heidelberg", "Heilbronn", "Heiligenblut", "Helena", "Helsinki", "Henderson", "Heraklion", "Herceg Novi", "Hereford", "Hermosa Beach", "Hervey Bay", "Hialeah", "Hillsboro", "Hinterglemm", "Hinterstoder", "Hiroshima", "Hoi An", "Hobart", "Ho Chi Minh City", "Hollywood (Florida)", "Honfleur", "Hong Kong", "Honolulu", "Horsens", "Hot Springs", "Houston", "Hua Hin", "Hue", "Huntington", "Huntington Beach", "Huntsville", "Hvar", "HyAĻres", "", "Ibiza Town", "Imola", "Imperia", "Inca", "Indianapolis", "Ingolstadt", "Innsbruck", "Interlaken", "Inverness", "Ioannina", "Irvine", "Irving", "Ischgl", "Isernia", "Islamorada", "Istanbul", "Ä°zmir", "Izola", "", "Jackson", "Jackson (Tennessee)", "Jacksonville", "Jefferson City", "Jena", "Jerez de la Frontera", "Jersey City", "Jerusalem", "Johannesburg", "Johnson City", "Joinville", "Jonesboro", "Juan-les-Pins", "Juiz de Fora", "Juneau", "Jungfrau", "Jupiter", "JÅŦrmala", "", "Kalamata", "Kalamazoo", "Kanchanaburi", "Kansas City", "Kansas City (Kansas)", "Kappl", "Kaprun", "Karlovy Vary", "Karlsruhe", "Kassel", "Kastoria", "Kaunas", "Kavala", "Kearney", "Keene", "Kemer", "Kenosha", "Key Largo", "Key West", "Khao Lak", "Kiel", "Kilkenny", "Kingston", "Kingston upon Hull", "Kissimmee", "KitzbAžhel", "Klagenfurt", "KlaipÄ&#151;da", "Knoxville", "Kobe", "Koblenz", "Kolding", "Komotini", "Koper", "Kos", "KoÅAice", "Kotor", "Krabi", "Krakow", "Krefeld", "Kuah", "Kuala Lumpur", "KuÅ&#159;adasÄA", "KutnAA Hora", "Kyoto", "Kyrenia", "", "La Ciotat", "La Clusaz", "La Laguna", "La Maddalena", "La Manga", "La Plagne", "La Plata", "La Rochelle", "La Romana", "La Serena", "La Spezia", "La Thuile", "Laax", "Lafayette (Indiana)", "Lafayette (Louisiana)", "Lagos", "Laguna Beach", "Lakeland", "Lamezia Terme", "Lancaster", "Lancaster (U.S.)", "Lansing", "L'Aquila", "Laredo", "Largo", "Larnaca", "Las Cruces", "Las Palmas", "Las Vegas", "Latina", "Lausanne", "Laval", "Lawton", "Layton", "Le Havre", "Le Lavandou", "Le Mans", "Lecce", "Lecco", "Lech", "Leeds", "Legnano", "Leicester", "Leiden", "Leipzig", "Leogang", "Les Arcs", "Les Deux Alpes", "Les Gets", "Les Houches", "Les Menuires", "Leuven", "Lexington", "Liberec", "Libreville", "Lichfield", "LiAĻge", "Lienz", "LiepÄja", "Lille", "Limassol", "Limerick", "Limoges", "Lincoln", "Lincoln", "Lindos", "Linz", "Lisbon", "Lisburn", "Little Rock", "Liverpool", "Livigno", "Livorno", "Ljubljana", "Lloret de Mar", "Loano", "Locarno", "Lodi", "Lodz", "Logan", "Logrono", "London (Canada)", "London (UK)", "Londrina", "Long Beach", "Long Beach (New York)", "Long Branch", "Longview (Texas)", "Longview (Washington)", "Lorain", "Los Alamos", "Los Angeles", "Los Cabos", "Los Cristianos", "Louisville", "Lourdes", "Loutraki", "Louvain-la-Neuve", "Lowell", "Luanda", "Lubbock", "LAžbeck", "Lublin", "Lucca", "Lucerne", "Lugano", "Lund", "Luxembourg", "Lyon", "", "Maastricht", "Macerata", "Macon", "Madera", "Madison", "Madonna di Campiglio", "Madrid", "Magaluf", "Magdeburg", "MahAģn", "Mainz", "Makarska", "Malaga", "Malia", "Malibu", "MalmAķ", "Manacor", "Manchester (UK)", "Manchester (U.S.)", "Manhattan Beach", "Mannheim", "Manosque", "Mantua", "Maputo", "Mar del Plata", "Marathon", "Marbella", "Maria Alm", "Maribor", "Markham", "Marmaris", "Maroochydore", "Marquette", "Marrakesh", "Marsala", "Marseille", "Martigues", "Maspalomas", "Massa", "Matera", "Mayrhofen", "Mazara del Vallo", "McKinney", "Mechelen", "Medford", "MegAĻve", "Melbourne (Australia)", "Melbourne (U.S.)", "Memphis", "Menton", "Merano", "Merced", "Meribel", "MAĐrida", "Meridian", "Mesa", "Messina", "Mestre", "Metz", "Mexico City", "Miami", "Middelburg", "Midland", "Mijas", "Milan", "Milford", "Millau", "Milwaukee", "Minneapolis", "Minot", "Miramar", "Mishawaka", "Mississauga", "Missoula", "Moab", "Mobile", "Modena", "Modesto", "Modica", "Moena", "Mogi das Cruzes", "Mons", "Monte Rosa", "Montego Bay", "Montepulciano", "Monterey", "Montgomery", "MontluA§on", "Montpelier", "Montpellier", "Montreal", "Montreux", "Monza", "Moraira", "Moreno Valley", "Morgantown", "Morzine", "Moscow", "Mount Vernon", "Mountain View", "Mulhouse", "Munich", "MAžnster", "Murcia", "Murfreesboro", "Murter", "Mykonos", "Mytilene", "", "Nafplio", "Nagoya", "Nags Head", "Namur", "Nancy", "Nantes", "Napa", "Naples (Italy)", "Naples (U.S.)", "Narbonne", "Narva", "Nashua", "Nashville", "Nassau", "Naxos", "Nazareth", "Negril", "Nelson", "Nerja", "Netanya", "Nevers", "New Haven", "New London", "New Orleans", "New Smyrna Beach", "New York City", "Newark", "Newcastle (Australia)", "Newcastle (UK)", "Newport (UK)", "Newport (Rhode Island)", "Newport (Vermont)", "Newport Beach", "Newport News", "Newry", "Nha Trang", "Niagara Falls", "Nice", "Nicosia", "Nijmegen", "Nimes", "Niort", "Noosa Heads", "Norfolk", "Normal", "Norman", "North Las Vegas", "North Port", "Norwalk", "Norwich", "Nottingham", "Novara", "Novigrad", "Nuoro", "NAžrnberg", "Nyon", "", "Oakland", "Oaxaca", "Obergurgl", "Oberhausen", "Ocala", "Ocean City", "Ocean Grove", "Oceanside", "Ocho Rios", "Odense", "Odessa", "Ogden", "Oia", "Oklahoma City", "Olbia", "Oldenburg", "Olomouc", "Olympia", "Omaha", "Opatija", "Orange Beach", "Orem", "Oristano", "Orlando", "OrlAĐans", "Ortisei", "Osaka", "Oshkosh", "Oslo", "OsnabrAžck", "Ostrava", "Ottawa", "Oulu", "Overland Park", "Oviedo", "Owensboro", "Oxford", "Oxnard", "Paderborn", "Padova", "Palanga", "Palavas-les-Flots", "Palermo", "Palm Bay", "Palm Beach", "Palm Springs", "Palma de Mallorca", "Palma Nova", "Palmetto", "Palo Alto", "Pamplona", "Panama City (U.S.)", "Paphos", "Paradiski", "Paralia", "Parikia", "Paris", "Parkersburg", "Parma", "PAĪrnu", "Pasadena", "Passo del Tonale", "Passo Rolle", "Paterson", "Patras", "Pattaya", "Pau", "Pavia", "Peguera", "Pembroke Pines", "Pensacola", "Peoria", "Perast", "PAĐrigueux", "Perpignan", "Perros-Guirec", "Perth (Australia)", "Perth (UK)", "Perugia", "Pesaro", "Pescara", "Pescasseroli", "Petah Tikva", "Peterborough", "Petrovac", "Pforzheim", "Phang Nga", "Phetchabun", "Philadelphia", "Phoenix", "Phuket City", "Piacenza", "Pierre", "Pine Bluff", "Piraeus", "Piran", "Pisa", "Pistoia", "Pittsburgh", "Placencia", "Plano", "Playa Blanca", "Playa de las AmAĐricas", "Playa del Carmen", "Plovdiv", "Plymouth", "PlzeÅ&#136;", "Podgorica", "Poitiers", "PollenA§a", "Pompano Beach", "Pontevedra", "Pordenone", "PoreÄ", "Port Angeles", "Port Charlotte", "Port St. Lucie", "Port Townsend", "Port-au-Prince", "PortimAĢo", "Portland (Oregon)", "Portland (Maine)", "Porto", "Porto Cervo", "Porto Cristo", "Porto Torres", "Portocolom", "Portofino", "PortoroÅū", "Porto-Vecchio", "Portsmouth (UK)", "Portsmouth (U.S.)", "Positano", "Potenza", "Potsdam", "Poznan", "Pozzuoli", "Prague", "Praia da Rocha", "Prato", "Preston", "Pretoria", "Propriano", "Protaras", "Providence", "Provo", "Pueblo", "Puerto de la Cruz", "Puerto Plata", "Puerto Rico de Gran Canaria", "Puerto Vallarta", "Pula", "Punta Arenas", "Punta Cana", "Punta Gorda", "Pyeongchang", "", "Quarteira", "Quebec", "Quimper", "", "Rabat", "Racine", "Ragusa", "Railay Beach", "Raleigh", "Rancho Cucamonga", "Randers", "Rapallo", "Rapid City", "Ras al-Khaimah", "Ravello", "Ravenna", "Rayong", "Reading", "Redding", "Redondo Beach", "Regensburg", "Reggio Calabria", "Reggio Emilia", "Regina", "Rehovot", "Reims", "Rennes", "Reno", "Rethymno", "Reus", "Reutlingen", "Reykjavik", "Rhodes", "Richmond", "Rieti", "Riga", "Rijeka", "Rimini", "Rio de Janeiro", "Riomaggiore", "Rishon LeZion", "Riverside", "Riviera Maya", "Roanoke", "Rochester (Minnesota)", "Rochester (New York)", "Rock Hill", "Rockford", "Rockville", "Rodez", "Rogers", "Rome", "Rosario", "Roskilde", "Rostock", "Roswell", "Rotterdam", "Roubaix", "Rouen", "Rovigo", "Rovinj", "Rutland", "", "Sa Coma", "Saalbach", "SaarbrAžcken", "Saas-Fee", "Sacramento", "Saint Paul", "Saint Petersburg", "Saint-Brieuc", "Sainte-Maxime", "Saint-A&#137;tienne", "Saint-Jean-Cap-Ferrat", "Saint-Malo", "Saint-Tropez", "Salamanca", "Salem (Oregon)", "Salem (Massachusetts)", "Salerno", "Salinas", "Salisbury", "Salou", "Salt Lake City", "Salta", "Salvador", "Salzburg", "SamanAA", "San Angelo", "San Antonio", "San Bernardino", "San Clemente", "San Diego", "San Francisco", "San Jose", "San Juan", "San Mateo", "San Pedro", "San Pedro de Atacama", "San Rafael", "San SebastiAAn", "Sanford", "Sanremo", "Sant Antoni de Portmany", "Santa Ana", "Santa Barbara", "Santa Clara", "Santa Clarita", "Santa Cruz", "Santa Cruz de Tenerife", "Santa EulA ria des Riu", "Santa Fe", "Santa Margherita Ligure", "Santa Monica", "Santa Pola", "Santa Ponsa", "Santa Rosa", "Santander", "Santiago (Chile)", "Santiago (Dominican Rep.)", "Santiago de Compostela", "Santo Domingo", "Sao Paulo", "Sapporo", "Sarajevo", "Sarasota", "Saratoga Springs", "Saskatoon", "Sassari", "Saumur", "Savannah", "Savona", "Schaffhausen", "Schenectady", "Schladming", "Scottsdale", "Scranton", "Sea Isle City", "Seal Beach", "Seaside", "Seattle", "Sedona", "Seefeld", "Segovia", "Seoul", "Serre Chevalier", "SAĻte", "Seville", "Shanghai", "Sharjah", "Sheffield", "Shenzhen", "Shreveport", "Å iauliai", "Å ibenik", "Side", "Siegen", "Siena", "Singapore", "Sion", "Sioux City", "Sioux Falls", "Sitges", "Skiathos", "Sofia", "SAķlden", "SAķll", "Soller", "Solothurn", "Sondrio", "Sopot", "Sorocaba", "Sorrento", "South Bend", "Southampton", "Split", "Spokane", "Springdale", "Springfield (Illinois)", "Springfield (Massachusetts)", "Springfield (Missouri)", "Springfield (Oregon)", "St Albans", "St. Albans", "St. Anton", "St. Augustine", "St. Cloud", "St. Gallen", "St. George", "St. John's", "St. Louis", "St. Moritz", "St. Petersburg (U.S.)", "Stamford", "Stavanger", "Stillwater", "Stirling", "Stockholm", "Stockton", "Stoke-on-Trent", "Stone Harbor", "Strasbourg", "Stuttgart", "Sukhothai", "Sumter", "Sunderland", "Sunnyvale", "Sunshine Coast", "Superior", "Surrey", "Sveti Stefan", "Swansea", "Sydney", "Syracuse (Italy)", "Syracuse (U.S.)", "Szczecin", "", "Tacoma", "Taipei", "Tallahassee", "Tallinn", "Tampa", "Tampere", "Tamworth", "Tangier", "Taormina", "Taranto", "Tarifa", "Tarragona", "Tartu", "Tauplitz", "Tauranga", "Tavira", "Tbilisi", "Tel Aviv", "Temecula", "Tempe", "Teramo", "Terni", "Texarkana AR", "Texarkana TX", "The Hague", "The Woodlands", "Thessaloniki", "Tignes", "Tijuana", "Tilburg", "Tinos", "Tivat", "Tivoli", "Tokyo", "Toledo (Spain)", "Toledo (U.S.)", "Tooele", "Toowoomba", "Topeka", "Toronto", "Torre del Greco", "Torre del Mar", "Torremolinos", "Torrevieja", "ToruÅ&#132;", "Tossa de Mar", "Toulon", "Toulouse", "Tours", "Townsville", "Trani", "Trapani", "Trento", "Trenton", "Treviso", "Trier", "Trieste", "Trogir", "TromsAļ", "Trondheim", "Trouville-sur-Mer", "Troy", "Troyes", "Tucson", "Tui", "Tulsa", "Tulum", "Turin", "Turku", "Tuscaloosa", "Twin Falls", "Two Harbors", "Tybee Island", "Tyler", "", "Udine", "Udon Thani", "Ukiah", "Ulcinj", "Ulm", "Umag", "Uppsala", "Urbino", "Ushuaia", "Utica", "Utrecht", "", "Vaduz", "Val dâ&#128;&#153;IsAĻre", "Val di Fassa", "Val Gardena", "Val Thorens", "Valence", "Valencia", "Valladolid", "Valle Isarco", "Valletta", "ValparaA­so", "Vancouver (Canada)", "Vancouver (U.S.)", "Varazze", "Varese", "Varna", "Vaughan", "Vejle", "Venice (Italy)", "Venice (U.S.)", "Ventimiglia", "Ventspils", "Ventura", "Verbania", "Verbier", "Vercelli", "Vero Beach", "Verona", "Versailles", "Vevey", "Viareggio", "Vibo Valentia", "Viborg", "Vicenza", "Vichy", "Victoria", "Vienna", "Vigo", "Vilamoura", "Villach", "Villefranche-sur-Mer", "Vilnius", "Vina del Mar", "Virginia Beach", "Visalia", "Viterbo", "Vitoria-Gasteiz", "Volos", "Vrsar", "", "Waco", "Wakefield", "Warsaw", "Warth", "Washington D.C.", "Waterford", "Watertown", "Waukegan", "Waukesha", "Wellington (New Zealand)", "Wellington (U.S.)", "Wengen", "West Lafayette", "West Palm Beach", "Westendorf", "Westminster", "Weston", "Wheeling", "White Plains", "Wichita", "Wichita Falls", "Wiesbaden", "Wildwood", "Wilkes-Barre", "Wilmington (Delaware)", "Wilmington (North Carolina)", "Winchester", "Windsor", "Winnipeg", "Winstonâ&#128;&#147;Salem", "Winterthur", "Wolfsburg", "Wollongong", "Wolverhampton", "Woodburn", "Worcester (UK)", "Worcester (U.S.)", "Worthing", "Wroclaw", "Wuppertal", "WAžrzburg", "", "", "Yakima", "Yokohama", "Yonkers", "York (UK)", "York (U.S.)", "Youngstown", "Yuma", "", "Zadar", "Zagreb", "Zakopane", "Zaragoza", "Zell am See", "Zell am Ziller", "Zermatt", "Zug", "Zurich", "Zwolle"};

}
